import React from 'react';

import styled from 'styled-components';
import tw from 'tailwind-styled-components';

import Container from '../../layout/Container';

const Column = tw.div`
  max-w-3xl
  mx-auto
  mt-0
  sm:mt-4
  px-0
  md:px-6
  lg:px-0
`;

const PolicyHeading = tw.h1`
  text-3xl
  xsm:text-4xl
  md:text-5.25xl
  leading-9
  md:leading-14
  font-bold
  mb-6
`;

const Section = styled.div`
  margin-bottom: 3rem;

  a {
    color: #2c87f0 !important;
  }
  a:visited {
    color: #636 !important;
  }
  a:hover,
  a:active,
  a:focus {
    color: #c33 !important;
  }
`;

const Paragraph = tw.div`
  mb-3
`;

const SectionTitle = tw.h3`
  font-bold
  mb-2
`;

const PrivacyPolicyPage = () => {

  return (
    <Container>
      <Column>
        <PolicyHeading>Privacy Policy</PolicyHeading>
        <Section>
          <Paragraph>
            Engage Labs PBC DBA Engage (&quot;us&quot;, &quot;we&quot;, or
            &quot;our&quot;) operates the{' '}
            <a href="https://www.engagepolitics.com">
              https://www.engagepolitics.com
            </a>{' '}
            website (hereinafter referred to as the &quot;Service&quot;).
          </Paragraph>
          <Paragraph>
            This page informs you of our policies regarding the collection, use
            and disclosure of personal data when you use our Service and the
            choices you have associated with that data.
          </Paragraph>
          <Paragraph>
            We use your data to provide and improve the Service. By using the
            Service, you agree to the collection and use of information in
            accordance with this policy. Unless otherwise defined in this
            Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms of Service , accessible from{' '}
            <a href="http://www.engagepolitics.com/terms-of-service">
              http://www.engagepolitics.com/terms-of-service
            </a>
            .
          </Paragraph>
        </Section>
        <SectionTitle>Definitions</SectionTitle>
        <Section>
          <SectionTitle>Service</SectionTitle>
          Service is the platform and all content and information contained on
          the{' '}
          <a href="http://www.engagepolitics.com">
            http://www.engagepolitics.com
          </a>{' '}
          website operated by Engage Labs PBC DBA Engage
        </Section>
        <Section>
          <SectionTitle>Personal Data</SectionTitle>
          Personal Data means any data, information or a combination of data and
          information provided by you to us or through your use of the Service
          which relates to an identifiable individual (or from those and other
          information either in our possession or likely to come into our
          possession).
        </Section>
        <Section>
          <SectionTitle>Usage Data</SectionTitle>Usage Data is data collected
          automatically either generated by the use of the Service or from the
          Service infrastructure itself (for example, the duration of a page
          visit).
        </Section>
        <Section>
          <SectionTitle>Cookies</SectionTitle>Cookies are small files stored on
          your device (computer or mobile device).
        </Section>
        <Section>
          <SectionTitle>Data Controller</SectionTitle>
          <Paragraph>
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed.
          </Paragraph>
          For the purpose of this Privacy Policy, we are a Data Controller of
          your Personal Data.
        </Section>
        <Section>
          <SectionTitle>Data Processors (or Service Providers)</SectionTitle>{' '}
          Data Processor (or Service Provider) means any natural or legal person
          who processes the data on behalf of the Data Controller. We may use
          the services of various Service Providers in order to process your
          data more effectively.
        </Section>
        <Section>
          <SectionTitle>Data Subject (or User)</SectionTitle> Data Subject is
          any living individual who is using our Service and is the subject of
          Personal Data.
        </Section>
        <Section>
          <SectionTitle>Information Collection and Use</SectionTitle>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </Section>{' '}
        <SectionTitle>Types of Data Collected</SectionTitle>
        <Section>
          Personal Data While using our Service, we may ask you to provide us
          with certain personally identifiable information that can be used to
          contact or identify you (&quot;Personal Data&quot;). Personally
          identifiable information may include, but is not limited to:{' '}
          <Paragraph>- Email address</Paragraph>
          <Paragraph>- Company name</Paragraph>
          <Paragraph>- First name and last name</Paragraph>
          <Paragraph>- Phone number</Paragraph>
          <Paragraph>
            - Address, State, Province, ZIP/Postal code, City
          </Paragraph>
          <Paragraph>- Cookies and Usage Data</Paragraph>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link or
          instructions provided in any email we send to you or by contacting us
          directly.
        </Section>
        <Section>
          <SectionTitle>Usage Data</SectionTitle> We may also collect
          information on how the Service is accessed and used (&quot;Usage
          Data&quot;). This Usage Data may include information such as your
          computer&apos;s Internet Protocol address (e.g. IP address), browser
          type, browser version, the pages of our Service that you visit, the
          time and date of your visit, the time spent on those pages, unique
          device identifiers and other diagnostic data.
        </Section>
        <Section>
          <SectionTitle>Location Data</SectionTitle> We may use and store
          information about your location if you give us permission to do so
          (&quot;Location Data&quot;). We use this data to provide features of
          our Service, to improve and customise our Service. You can enable or
          disable location services when you use our Service at any time by way
          of your device settings.
        </Section>
        <Section>
          <SectionTitle>Tracking Cookies</SectionTitle>
          Data We use cookies and similar tracking technologies to track the
          activity on our Service and we hold certain information. Cookies are
          files with a small amount of data which may include an anonymous
          unique identifier. Cookies are sent to your browser from a website and
          stored on your device. Other tracking technologies are also used such
          as beacons, tags and scripts to collect and track information and to
          improve and analyse our Service. You can instruct your browser to
          refuse all cookies or to indicate when a cookie is being sent.
          However, if you do not accept cookies, you may not be able to use some
          or all portions of our Service.
        </Section>
        <Section>
          <SectionTitle>Examples of Cookies we use:</SectionTitle>- Session
          Cookies. We use Session Cookies to operate our Service. - Preference
          Cookies. We use Preference Cookies to remember your preferences and
          various settings. - Security Cookies. We use Security Cookies for
          security purposes. - Advertising Cookies. Advertising Cookies are used
          to serve you with advertisements that may be relevant to you and your
          interests. - Use of Data
        </Section>
        <Section>
          <SectionTitle>
            Engage Labs PBC DBA Engage uses the collected data for various
            purposes:
          </SectionTitle>
          - To provide and maintain our Service - To notify you about changes to
          our Service - To allow you to participate in interactive features of
          our Service when you choose to do so - To provide customer support -
          To gather analysis or valuable information so that we can improve our
          Service for you - To monitor the usage of our Service - To detect,
          prevent and address technical issues - To provide you with news,
          special offers and general information about other goods, services and
          events which we offer that are similar to those that you have already
          purchased or enquired about unless you have opted not to receive such
          information
        </Section>
        <Section>
          <SectionTitle>
            Legal Basis for Processing Personal Data under the General Data
            Protection Regulation (GDPR)
          </SectionTitle>
          If you are from the European Economic Area (EEA), Engage Labs PBC DBA
          Engage legal basis for collecting and using the personal information
          described in this Privacy Policy depends on the Personal Data we
          collect and the specific context in which we collect it. Engage Labs
          PBC DBA Engage may process your Personal Data because: - We need to
          perform a contract with you - You have given us permission to do so -
          The processing is in our legitimate interests and it is not overridden
          by your rights - To comply with the law - Retention of Data Engage
          Labs PBC DBA Engage will retain your Personal Data only for as long as
          is necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes and/or
          enforce our legal agreements and policies. Engage Labs PBC DBA Engage
          will also retain Usage Data for internal analysis purposes. Usage Data
          is generally retained for a shorter period of time, except when this
          data is used to strengthen the security or to improve the
          functionality of our Service, or we are legally obligated to retain
          this data for longer periods.
        </Section>
        <Section>
          <SectionTitle>Transfer of Data</SectionTitle>
          Your information, including Personal Data, may be transferred to — and
          maintained on — computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction. If you are located
          outside United States and choose to provide information to us, please
          note that we transfer the data, including Personal Data, to the United
          States and process it there. Your consent to this Privacy Policy
          followed by your submission of such information represents your
          agreement to that transfer of data. Engage Labs PBC DBA Engage will
          take all the steps reasonably necessary to ensure that your data is
          treated securely and in accordance with this Privacy Policy and no
          transfer of your Personal Data will take place to a third party unless
          there are adequate controls in place including the security of your
          data and other personal information.
        </Section>
        <SectionTitle>Disclosure of Data</SectionTitle>
        <Section>
          <SectionTitle>Business Transaction</SectionTitle>
          If Engage Labs PBC DBA Engage is involved in a merger, acquisition or
          asset sale, your Personal Data may be transferred. We will provide
          notice before your Personal Data is transferred and becomes subject to
          a different Privacy Policy.
        </Section>
        <Section>
          <SectionTitle>Disclosure for Law Enforcement</SectionTitle> Under
          certain circumstances, Engage Labs PBC DBA Engage may be required to
          disclose your Personal Data if required to do so by law or in response
          to valid requests by public authorities (e.g. a court or a government
          agency).
        </Section>
        <Section>
          <SectionTitle>Legal Requirements</SectionTitle>
          Engage Labs PBC DBA Engage may disclose your Personal Data in the good
          faith belief that such action is necessary to: - To comply with a
          legal obligation - To protect and defend the rights or property of
          Engage Labs PBC DBA Engage - To prevent or investigate possible
          wrongdoing in connection with the Service - To protect the personal
          safety of users of the Service or the public - To protect against
          legal liability
        </Section>
        <Section>
          <SectionTitle>Security of Data</SectionTitle> The security of your
          data is important to us but remember that no method of transmission
          over the Internet or method of electronic storage is 100% secure.
          While we strive to use commercially acceptable means to protect your
          Personal Data, we cannot guarantee its absolute security.
        </Section>
        <Section>
          <SectionTitle>
            Our Policy on &quot;Do Not Track&quot; Signals under the California
            Online Protection Act (CalOPPA)
          </SectionTitle>
          We do not support Do Not Track (&quot;DNT&quot;). Do Not Track is a
          preference you can set in your web browser to inform websites that you
          do not want to be tracked. You can enable or disable Do Not Track by
          visiting the Preferences or Settings page of your web browser.
        </Section>
        <Section>
          <SectionTitle>
            Your Data Protection Rights under the General Data Protection
            Regulation (GDPR)
          </SectionTitle>
          If you are a resident of the European Economic Area (EEA), you have
          certain data protection rights. Engage Labs PBC DBA Engage aims to
          take reasonable steps to allow you to correct, amend, delete or limit
          the use of your Personal Data. If you wish to be informed about what
          Personal Data we hold about you and if you want it to be removed from
          our systems, please contact us. In certain circumstances, you have the
          following data protection rights: - The right to access, update or
          delete the information we have on you. Whenever made possible, you can
          access, update or request deletion of your Personal Data directly
          within your account settings Section. If you are unable to perform
          these actions yourself, please contact us to assist you. - The right
          of rectification. You have the right to have your information
          rectified if that information is inaccurate or incomplete. - The right
          to object. You have the right to object to our processing of your
          Personal Data. - The right of restriction. You have the right to
          request that we restrict the processing of your personal information.
          - The right to data portability. You have the right to be provided
          with a copy of the information we have on you in a structured,
          machine-readable and commonly used format. - The right to withdraw
          consent. You also have the right to withdraw your consent at any time
          where Engage Labs PBC DBA Engage relied on your consent to process
          your personal information. Please note that we may ask you to verify
          your identity before responding to such requests. You have the right
          to complain to a Data Protection Authority about our collection and
          use of your Personal Data. For more information, please contact your
          local data protection authority in the European Economic Area (EEA).
        </Section>
        <Section>
          <SectionTitle>Service Providers</SectionTitle> We may employ third
          party companies and individuals to facilitate our Service
          (&quot;Service Providers&quot;), provide the Service on our behalf,
          perform Service-related services or assist us in analysing how our
          Service is used. These third parties have access to your Personal Data
          only to perform these tasks on our behalf and are obligated not to
          disclose or use it for any other purpose.
        </Section>
        <Section>
          <SectionTitle>Plaid</SectionTitle> Engage Labs uses Plaid Inc.
          (“Plaid”) to gather your data from financial institutions. By using
          the Service, you grant Engage Labs and Plaid the right, power, and
          authority to act on your behalf to access and transmit your personal
          and financial information from your relevant financial institution.
          You agree to your personal and financial information being
          transferred, stored, and processed by Plaid in accordance with the
          Plaid end user privacy policy.
        </Section>
        <Section>
          <SectionTitle>Credit Card Information</SectionTitle> We securely
          transmit your credit card information to one of our payment
          processors. All credit card information is handled in accordance with
          current PCI standards.
        </Section>
        <Section>
          <SectionTitle>Analytics</SectionTitle> We may use third-party Service
          Providers to monitor and analyse the use of our Service.
        </Section>
        <Section>
          <SectionTitle>Google Analytics</SectionTitle> Google Analytics is a
          web analytics service offered by Google that tracks and reports
          website traffic. Google uses the data collected to track and monitor
          the use of our Service. This data is shared with other Google
          services. Google may use the collected data to contextualise and
          personalise the ads of its own advertising network. You can opt-out of
          having made your activity on the Service available to Google Analytics
          by installing the Google Analytics opt-out browser add-on. The add-on
          prevents the Google Analytics JavaScript (ga.js, analytics.js and
          dc.js) from sharing information with Google Analytics about visits
          activity. For more information on the privacy practices of Google,
          please visit the Google Privacy Terms web page:{' '}
          <a
            href="https://policies.google.com/privacy?hl=en"
            target="_blank"
            rel="noreferrer"
          >
            https://policies.google.com/privacy?hl=en
          </a>
        </Section>
        <Section>
          <SectionTitle>Piwik / Matomo</SectionTitle> Piwik or Matomo is a web
          analytics service. You can visit their Privacy Policy page here:{' '}
          <a
            href="https://matomo.org/privacy-policy"
            target="_blank"
            rel="noreferrer"
          >
            https://matomo.org/privacy-policy
          </a>
        </Section>
        <Section>
          <SectionTitle>Clicky</SectionTitle> Clicky is a web analytics service.
          Read the Privacy Policy for Clicky here:{' '}
          <a href="https://clicky.com/terms" target="_blank" rel="noreferrer">
            https://clicky.com/terms
          </a>
        </Section>
        <Section>
          <SectionTitle>Statcounter</SectionTitle> Statcounter is a web traffic
          analysis tool. You can read the Privacy Policy for Statcounter here:{' '}
          <a
            href="https://statcounter.com/about/legal/"
            target="_blank"
            rel="noreferrer"
          >
            https://statcounter.com/about/legal/
          </a>
        </Section>
        <Section>
          <SectionTitle>Mixpanel</SectionTitle> Mixpanel is provided by Mixpanel
          Inc. You can prevent Mixpanel from using your information for
          analytics purposes by opting-out. To opt-out of Mixpanel service,
          please visit this page:{' '}
          <a
            href="https://mixpanel.com/optout/"
            target="_blank"
            rel="noreferrer"
          >
            https://mixpanel.com/optout/
          </a>
          . For more information on what type of information Mixpanel collects,
          please visit the Terms of Use page of Mixpanel:{' '}
          <a
            href="https://mixpanel.com/terms/"
            target="_blank"
            rel="noreferrer"
          >
            https://mixpanel.com/terms/
          </a>
        </Section>
        <Section>
          <SectionTitle>Advertising</SectionTitle> We may use third-party
          Service Providers to show advertisements to you to help support and
          maintain our Service.
        </Section>
        <Section>
          <SectionTitle> Google AdSense DoubleClick Cookie</SectionTitle>{' '}
          Google, as a third party vendor, uses cookies to serve ads on our
          Service. Google&apos;s use of the DoubleClick cookie enables it and
          its partners to serve ads to our users based on their visit to our
          Service or other websites on the Internet. You may opt out of the use
          of the DoubleClick Cookie for interest-based advertising by visiting
          the Google Ads Settings web page:{' '}
          <a
            href="http://www.google.com/ads/preferences/"
            target="_blank"
            rel="noreferrer"
          >
            http://www.google.com/ads/preferences/
          </a>
        </Section>
        <Section>
          <SectionTitle>Bing Ads</SectionTitle> Bing Ads is an advertising
          service provided by Microsoft Inc. You can opt-out from Bing Ads by
          following the instructions on Bing Ads Opt-out page:{' '}
          <a
            href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads"
            target="_blank"
            rel="noreferrer"
          >
            https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads
          </a>
          . For more information about Bing Ads, please visit their Privacy
          Policy:{' '}
          <a
            href="https://privacy.microsoft.com/en-us/PrivacyStatement"
            target="_blank"
            rel="noreferrer"
          >
            https://privacy.microsoft.com/en-us/PrivacyStatement
          </a>
        </Section>
        <Section>
          <SectionTitle>AdButler</SectionTitle> AdButler is an advertising
          service provided by Sparklit Networks Inc. For more information about
          AdButler, please visit their Privacy Policy:{' '}
          <a
            href="https://www.sparklit.com/agreements.spark?agreement=privacy"
            target="_blank"
            rel="noreferrer"
          >
            https://www.sparklit.com/agreements.spark?agreement=privacy
          </a>
        </Section>
        <Section>
          <SectionTitle>Behavioral Remarketing</SectionTitle> Engage Labs PBC
          DBA Engage uses remarketing services to advertise on third party
          websites to you after you visited our Service. We and our third-party
          vendors use cookies to inform, optimise and serve ads based on your
          past visits to our Service.
        </Section>
        <Section>
          <SectionTitle>Google AdWords</SectionTitle> Google AdWords remarketing
          service is provided by Google Inc. You can opt-out of Google Analytics
          for Display Advertising and customise the Google Display Network ads
          by visiting the Google Ads Settings page:{' '}
          <a
            href="http://www.google.com/settings/ads"
            target="_blank"
            rel="noreferrer"
          >
            http://www.google.com/settings/ads
          </a>{' '}
          Google also recommends installing the Google Analytics Opt-out Browser
          Add-on -
          <a
            href="https://tools.google.com/dlpage/gaoptout"
            target="_blank"
            rel="noreferrer"
          >
            https://tools.google.com/dlpage/gaoptout
          </a>{' '}
          - for your web browser. Google Analytics Opt-out Browser Add-on
          provides visitors with the ability to prevent their data from being
          collected and used by Google Analytics. For more information on the
          privacy practices of Google, please visit the Google Privacy Terms web
          page:{' '}
          <a
            href="https://policies.google.com/privacy?hl=en"
            target="_blank"
            rel="noreferrer"
          >
            https://policies.google.com/privacy?hl=en
          </a>
        </Section>
        <Section>
          <SectionTitle>Bing Ads Remarketing</SectionTitle> Bing Ads remarketing
          service is provided by Microsoft Inc. You can opt-out of Bing Ads
          interest-based ads by following their instructions:{' '}
          <a
            href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads"
            target="_blank"
            rel="noreferrer"
          >
            https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads
          </a>
          . You can learn more about the privacy practices and policies of
          Microsoft by visiting their Privacy Policy page:{' '}
          <a
            href="https://privacy.microsoft.com/en-us/PrivacyStatement"
            target="_blank"
            rel="noreferrer"
          >
            https://privacy.microsoft.com/en-us/PrivacyStatement
          </a>
        </Section>
        <Section>
          <SectionTitle>Twitter</SectionTitle> Twitter remarketing service is
          provided by Twitter Inc. You can opt-out from Twitter&apos;s
          interest-based ads by following their instructions:{' '}
          <a
            href="https://support.twitter.com/articles/20170405"
            target="_blank"
            rel="noreferrer"
          >
            https://support.twitter.com/articles/20170405
          </a>
          . You can learn more about the privacy practices and policies of
          Twitter by visiting their Privacy Policy page:{' '}
          <a
            href="https://twitter.com/privacy"
            target="_blank"
            rel="noreferrer"
          >
            https://twitter.com/privacy
          </a>
        </Section>
        <Section>
          <SectionTitle>Facebook</SectionTitle> Facebook remarketing service is
          provided by Facebook Inc. You can learn more about interest-based
          advertising from Facebook by visiting this page:{' '}
          <a
            href="https://www.facebook.com/help/164968693837950"
            target="_blank"
            rel="noreferrer"
          >
            https://www.facebook.com/help/164968693837950
          </a>{' '}
          To opt-out from Facebook&apos;s interest-based ads, follow these
          instructions from Facebook:{' '}
          <a
            href="https://www.facebook.com/help/568137493302217"
            target="_blank"
            rel="noreferrer"
          >
            https://www.facebook.com/help/568137493302217
          </a>{' '}
          Facebook adheres to the Self-Regulatory Principles for Online
          Behavioural Advertising established by the Digital Advertising
          Alliance. You can also opt-out from Facebook and other participating
          companies through the Digital Advertising Alliance in the USA{' '}
          <a
            href="http://www.aboutads.info/choices/"
            target="_blank"
            rel="noreferrer"
          >
            http://www.aboutads.info/choices/
          </a>
          , the Digital Advertising Alliance of Canada in Canada{' '}
          <a href="http://youradchoices.ca/" target="_blank" rel="noreferrer">
            http://youradchoices.ca/
          </a>{' '}
          or the European Interactive Digital Advertising Alliance in Europe{' '}
          <a
            href="http://www.youronlinechoices.eu/"
            target="_blank"
            rel="noreferrer"
          >
            http://www.youronlinechoices.eu/
          </a>
          , or opt-out using your mobile device settings. For more information
          on the privacy practices of Facebook, please visit Facebook&apos;s
          Data Policy:{' '}
          <a
            href="https://www.facebook.com/privacy/explanation"
            target="_blank"
            rel="noreferrer"
          >
            https://www.facebook.com/privacy/explanation
          </a>
        </Section>
        <Section>
          <SectionTitle>Pinterest</SectionTitle> Pinterest remarketing service
          is provided by Pinterest Inc. You can opt-out from Pinterest&apos;s
          interest-based ads by enabling the &quot;Do Not Track&quot;
          functionality of your web browser or by following Pinterest
          instructions:{' '}
          <a
            href="http://help.pinterest.com/en/articles/personalization-and-data"
            target="_blank"
            rel="noreferrer"
          >
            http://help.pinterest.com/en/articles/personalization-and-data
          </a>{' '}
          You can learn more about the privacy practices and policies of
          Pinterest by visiting their Privacy Policy page:{' '}
          <a
            href="https://about.pinterest.com/en/privacy-policy"
            target="_blank"
            rel="noreferrer"
          >
            https://about.pinterest.com/en/privacy-policy
          </a>
        </Section>
        <Section>
          <SectionTitle>AdRoll</SectionTitle> AdRoll remarketing service is
          provided by Semantic Sugar, Inc. You can opt-out of AdRoll remarketing
          by visiting this AdRoll Advertising Preferences web page:{' '}
          <a
            href="http://info.evidon.com/pub_info/573?v=1nt=1nw=false"
            target="_blank"
            rel="noreferrer"
          >
            http://info.evidon.com/pub_info/573?v=1nt=1nw=false
          </a>{' '}
          For more information on the privacy practices of AdRoll, please visit
          the AdRoll Privacy Policy web page:{' '}
          <a
            href="http://www.adroll.com/about/privacy"
            target="_blank"
            rel="noreferrer"
          >
            http://www.adroll.com/about/privacy
          </a>
        </Section>
        <Section>
          <SectionTitle>Perfect Audience</SectionTitle> Perfect Audience
          remarketing service is provided by NowSpots Inc. You can opt-out of
          Perfect Audience remarketing by visiting these pages: Platform Opt-out
          (
          <a href="http://pixel.prfct.co/coo" target="_blank" rel="noreferrer">
            http://pixel.prfct.co/coo
          </a>
          ) and Partner Opt-out (
          <a href="http://ib.adnxs.com/optout" target="_blank" rel="noreferrer">
            http://ib.adnxs.com/optout
          </a>
          ). For more information on the privacy practices of Perfect Audience,
          please visit the Perfect Audience Privacy Policy Opt-out web page:{' '}
          <a
            href="https://www.perfectaudience.com/privacy/index.html"
            target="_blank"
            rel="noreferrer"
          >
            https://www.perfectaudience.com/privacy/index.html
          </a>
        </Section>
        <Section>
          <SectionTitle>AppNexus</SectionTitle> AppNexus remarketing service is
          provided by AppNexus Inc. You can opt-out of AppNexus remarketing by
          visiting the Privacy the AppNexus Platform web page:{' '}
          <a
            href="http://www.appnexus.com/platform-policy#choices"
            target="_blank"
            rel="noreferrer"
          >
            http://www.appnexus.com/platform-policy#choices
          </a>{' '}
          For more information on the privacy practices of AppNexus, please
          visit the AppNexus Platform Privacy Policy web page:{' '}
          <a
            href="http://www.appnexus.com/platform-policy/"
            target="_blank"
            rel="noreferrer"
          >
            http://www.appnexus.com/platform-policy/
          </a>
        </Section>
        <Section>
          <SectionTitle>Links to Other Sites</SectionTitle> Our Service may
          contain links to other sites that are not operated by us. If you click
          a third party link, you will be directed to that third party&apos;s
          site. We strongly advise you to review the Privacy Policy of every
          site you visit. We have no control over and assume no responsibility
          for the content, privacy policies or practices of any third party
          sites or services.
        </Section>
        <Section>
          <SectionTitle>Children&apos;s Privacy</SectionTitle> Our Service does
          not address anyone under the age of 18 (&quot;Children&quot;). We do
          not knowingly collect personally identifiable information from anyone
          under the age of 18. If you are a parent or guardian and you are aware
          that your Child has provided us with Personal Data, please contact us.
          If we become aware that we have collected Personal Data from children
          without verification of parental consent, we take steps to remove that
          information from our servers.
        </Section>
        <Section>
          <SectionTitle>Changes to This Privacy Policy</SectionTitle> We may
          update our Privacy Policy from time to time. Changes and updates will
          of course be posted here. You are advised to review this Privacy
          Policy periodically for any changes. Changes to this Privacy Policy
          are effective when they are posted on this page.
        </Section>
        <Section>
          <SectionTitle>Contact Us</SectionTitle> If you have any questions
          about this Privacy Policy, please contact us by email:{' '}
          <a href="mailto:info@engagepolitics.com">info@engagepolitics.com</a>
        </Section>
      </Column>
    </Container>
  );
};

export default PrivacyPolicyPage;
